<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[opened windows:[38B2D1F490EF63D80F20EDCD4D3F4FA9, ADED43DD55F4548F0FA1AA66D0AB5C1B]]]>
    </line>
    <line>
      <![CDATA[Current Window Count:1]]>
    </line>
    <line>
      <![CDATA[opened windows:[5EE5A33790025CE4EE3EEBD63C9E3359, 166E35B9A4AA693FC5414E3DC423D317]]]>
    </line>
    <line>
      <![CDATA[Current Window Count:1]]>
    </line>
  </reporter-output>
  <suite started-at="2025-10-30T14:21:03 CDT" name="Suite" finished-at="2025-10-30T14:21:38 CDT" duration-ms="35663">
    <groups>
    </groups>
    <test started-at="2025-10-30T14:21:03 CDT" name="Chrome Test" finished-at="2025-10-30T14:21:20 CDT" duration-ms="17593">
      <class name="advancedSelenium.SeleniumAdvanced">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@385e9564]" started-at="2025-10-30T14:21:03 CDT" name="setUp" finished-at="2025-10-30T14:21:09 CDT" duration-ms="6184" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[128.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Windows 10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="launchPage(java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@385e9564]" started-at="2025-10-30T14:21:09 CDT" name="launchPage" finished-at="2025-10-30T14:21:11 CDT" duration-ms="2688" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchPage -->
        <test-method signature="testScenario()[pri:0, instance:advancedSelenium.SeleniumAdvanced@385e9564]" started-at="2025-10-30T14:21:11 CDT" name="testScenario" finished-at="2025-10-30T14:21:20 CDT" duration-ms="8538" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at advancedSelenium.SeleniumAdvanced.testScenario(SeleniumAdvanced.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:33)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:353)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:308)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:696)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[opened windows:[38B2D1F490EF63D80F20EDCD4D3F4FA9, ADED43DD55F4548F0FA1AA66D0AB5C1B]]]>
            </line>
            <line>
              <![CDATA[Current Window Count:1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testScenario -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:advancedSelenium.SeleniumAdvanced@385e9564]" started-at="2025-10-30T14:21:20 CDT" name="teardown" finished-at="2025-10-30T14:21:20 CDT" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- advancedSelenium.SeleniumAdvanced -->
    </test> <!-- Chrome Test -->
    <test started-at="2025-10-30T14:21:20 CDT" name="Microsoft Edge Test" finished-at="2025-10-30T14:21:38 CDT" duration-ms="17967">
      <class name="advancedSelenium.SeleniumAdvanced">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@76ed1b7c]" started-at="2025-10-30T14:21:20 CDT" name="setUp" finished-at="2025-10-30T14:21:29 CDT" duration-ms="8992" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Microsoft Edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[127.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[macOS Ventura]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="launchPage(java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@76ed1b7c]" started-at="2025-10-30T14:21:29 CDT" name="launchPage" finished-at="2025-10-30T14:21:31 CDT" duration-ms="1903" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchPage -->
        <test-method signature="testScenario()[pri:0, instance:advancedSelenium.SeleniumAdvanced@76ed1b7c]" started-at="2025-10-30T14:21:31 CDT" name="testScenario" finished-at="2025-10-30T14:21:38 CDT" duration-ms="6855" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at advancedSelenium.SeleniumAdvanced.testScenario(SeleniumAdvanced.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:33)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:353)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:308)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:696)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[opened windows:[5EE5A33790025CE4EE3EEBD63C9E3359, 166E35B9A4AA693FC5414E3DC423D317]]]>
            </line>
            <line>
              <![CDATA[Current Window Count:1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testScenario -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:advancedSelenium.SeleniumAdvanced@76ed1b7c]" started-at="2025-10-30T14:21:38 CDT" name="teardown" finished-at="2025-10-30T14:21:38 CDT" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- advancedSelenium.SeleniumAdvanced -->
    </test> <!-- Microsoft Edge Test -->
  </suite> <!-- Suite -->
</testng-results>
