<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[opened windows:[B74F375A88494EF28123F0DFC0C4AF5C, 9F79F2E237DECA662A20550648237869]]]>
    </line>
    <line>
      <![CDATA[Current Window Count:1]]>
    </line>
    <line>
      <![CDATA[opened windows:[C3E40E9CB1223D5497F76FB37B9F2A13, BC9439B09EB03464AB905643E1148CF5]]]>
    </line>
    <line>
      <![CDATA[Current Window Count:1]]>
    </line>
  </reporter-output>
  <suite started-at="2025-10-30T14:09:51 CDT" name="Suite" finished-at="2025-10-30T14:10:33 CDT" duration-ms="42054">
    <groups>
    </groups>
    <test started-at="2025-10-30T14:09:51 CDT" name="Chrome Test" finished-at="2025-10-30T14:10:16 CDT" duration-ms="24460">
      <class name="advancedSelenium.SeleniumAdvanced">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@5b94b04d]" started-at="2025-10-30T14:09:51 CDT" name="setUp" finished-at="2025-10-30T14:10:03 CDT" duration-ms="11269" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[128.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Windows 10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="launchPage(java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@5b94b04d]" started-at="2025-10-30T14:10:03 CDT" name="launchPage" finished-at="2025-10-30T14:10:06 CDT" duration-ms="3486" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchPage -->
        <test-method signature="testScenario()[pri:0, instance:advancedSelenium.SeleniumAdvanced@5b94b04d]" started-at="2025-10-30T14:10:06 CDT" name="testScenario" finished-at="2025-10-30T14:10:16 CDT" duration-ms="9482" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at advancedSelenium.SeleniumAdvanced.testScenario(SeleniumAdvanced.java:132)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:33)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:353)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:308)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:696)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[opened windows:[B74F375A88494EF28123F0DFC0C4AF5C, 9F79F2E237DECA662A20550648237869]]]>
            </line>
            <line>
              <![CDATA[Current Window Count:1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testScenario -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:advancedSelenium.SeleniumAdvanced@5b94b04d]" started-at="2025-10-30T14:10:16 CDT" name="teardown" finished-at="2025-10-30T14:10:16 CDT" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- advancedSelenium.SeleniumAdvanced -->
    </test> <!-- Chrome Test -->
    <test started-at="2025-10-30T14:10:16 CDT" name="Microsoft Edge Test" finished-at="2025-10-30T14:10:33 CDT" duration-ms="17466">
      <class name="advancedSelenium.SeleniumAdvanced">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@11fc564b]" started-at="2025-10-30T14:10:16 CDT" name="setUp" finished-at="2025-10-30T14:10:25 CDT" duration-ms="8582" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Microsoft Edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[127.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[macOS Ventura]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="launchPage(java.lang.String)[pri:0, instance:advancedSelenium.SeleniumAdvanced@11fc564b]" started-at="2025-10-30T14:10:25 CDT" name="launchPage" finished-at="2025-10-30T14:10:27 CDT" duration-ms="1960" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchPage -->
        <test-method signature="testScenario()[pri:0, instance:advancedSelenium.SeleniumAdvanced@11fc564b]" started-at="2025-10-30T14:10:27 CDT" name="testScenario" finished-at="2025-10-30T14:10:33 CDT" duration-ms="6739" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TestingWhiz Integration With LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest],
expected [https://community.lambdatest.com] but found [https://community.lambdatest.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at advancedSelenium.SeleniumAdvanced.testScenario(SeleniumAdvanced.java:132)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:33)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:353)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:308)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:696)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[opened windows:[C3E40E9CB1223D5497F76FB37B9F2A13, BC9439B09EB03464AB905643E1148CF5]]]>
            </line>
            <line>
              <![CDATA[Current Window Count:1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testScenario -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:advancedSelenium.SeleniumAdvanced@11fc564b]" started-at="2025-10-30T14:10:33 CDT" name="teardown" finished-at="2025-10-30T14:10:33 CDT" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- advancedSelenium.SeleniumAdvanced -->
    </test> <!-- Microsoft Edge Test -->
  </suite> <!-- Suite -->
</testng-results>
